#!/bin/bash

#SBATCH --time=00:05:00   # walltime
#SBATCH --ntasks=4   # number of processor cores (i.e. tasks)
#SBATCH --nodes=1   # number of nodes
#SBATCH --mem-per-cpu=1024M   # memory per CPU core
#SBATCH --mail-user=liamnguy@byu.edu   # email address
#SBATCH --mail-type=END
#SBATCH --mail-type=FAIL
#SBATCH --job-name=ODE_Explicit_Euler
#SBATCH --output=Vector_Outputs.out

module load gcc

cd /home/liamnguy/training/src
srun ./Comp_Solve

